# Generated by Django 4.2.13 on 2024-06-15 16:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import djrichtextfield.models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Meta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Recipe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=300)),
                ("description", models.CharField(max_length=500)),
                (
                    "instructions",
                    djrichtextfield.models.RichTextField(max_length=10000),
                ),
                ("ingredients", djrichtextfield.models.RichTextField(max_length=10000)),
                (
                    "meal_type",
                    models.CharField(
                        choices=[
                            ("colazione", "Colazione"),
                            ("pranzo", "Pranzo"),
                            ("cena", "Cena"),
                        ],
                        default="Colazione",
                        max_length=50,
                    ),
                ),
                (
                    "cuisine_type",
                    models.CharField(
                        choices=[
                            ("africana", "Africana"),
                            ("americana", "Americana"),
                            ("asian", "Asian"),
                            ("chinese", "Chinese"),
                            ("indian", "Indian"),
                            ("italian", "Italian"),
                            ("other", "Other"),
                        ],
                        default="Other",
                        max_length=50,
                    ),
                ),
                ("posted_date", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recipe_owner",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
