# Generated by Django 4.2.13 on 2024-06-18 19:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("recipes", "0002_alter_recipe_cuisine_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipe",
            name="favourite",
            field=models.ManyToManyField(
                blank=True, related_name="favourites", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
